# Generated by Django 4.0.6 on 2022-07-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='greeting',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
